
all: .SYMBOLIC

     cd append
     $(MAKE)
     cd ..

     cd attrib
     $(MAKE)
     cd ..

     cd choice
     $(MAKE)
     cd ..

     cd deltree
     $(MAKE)
     cd ..

     cd diskcomp
     $(MAKE)
     cd ..

#     cd diskcopy
#     $(MAKE)
#     cd ..

#     cd edit
#     $(MAKE)
#     cd ..

     cd edlin
     $(MAKE)
     cd ..

     cd fc
     $(MAKE)
     cd ..

     cd fdapm
     $(MAKE)
     cd ..

#     cd fdisk
#     $(MAKE)
#     cd ..

#     cd find
#     $(MAKE)
#     cd ..

     cd format
     $(MAKE)
     cd ..

     cd label
     $(MAKE)
     cd ..

     cd lbacache
     $(MAKE)
     cd ..

     cd mem
     $(MAKE)
     cd ..

#     cd mode
#     $(MAKE)
#     cd ..

     cd more
     $(MAKE)
     cd ..

     cd move
     $(MAKE)
     cd ..

     cd nlsfunc
     $(MAKE)
     cd ..

     cd print
     $(MAKE)
     cd ..

     cd replace
     $(MAKE)
     cd ..

     cd sort
     $(MAKE)
     cd ..

     cd tree
     $(MAKE)
     cd ..

     cd xcopy
     $(MAKE)
     cd ..

