# Makefile for FreeDOS EDLIN
# uses OpenWatcom (MAKEFILE.OW is based on MAKEFILE.BC)

CC=wcl
CFLAGS=-mc -DHAVE_CONFIG_H
LDFLAGS=
LDLIBS=

SOURCES=defines.c dynstr.c edlib.c edlin.c 
OBJ=$(SOURCES:.c=.obj)
EXE=edlin.exe

all: edlin.exe

edlin.exe: config.h
	$(CC) $(CFLAGS) $(LDFLAGS) -fe=$(EXE) $(SOURCES) $(LDLIBS)

config.h:
	-copy config-h.ow config.h

clean:
	-del *.obj

realclean: clean
	-del config.h

distclean: realclean
	-del $(EXE)
